### ISSUE TITLE
Installation in Google ColaB

### ISSUE THREAD

**Issue by martinpius** [tomer1812/pydts#1]
Installation  via CoLaB isn’t working.

**Comment by tomer1812** [comment]
Hi @martinpius ,

Thank you for your comment. 
The current default python version in google colab is 3.7.14 while pydts requires python 3.8+.

I was able to install and use pydts in Colab after upgrading the python version and the pip version using the following steps:

# Upgrading python and pip versions
!sudo apt-get update -y
!sudo apt-get install python3.9
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2
!sudo apt install python3.9-distutils
!sudo apt-get install python3-pip
!python -m pip install --upgrade pip
!pip install --upgrade setuptools

# Installing pydts
!pip install pydts

# Importing pydts
import sys
sys.path.append('/usr/local/lib/python3.9/dist-packages')
import pydts
